audit_header: false
title: San Diego Real Estate Video Blog with John Stenberg
description: Our mission at The Stenberg Real Estate Group is to be your best resource for San Diego real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Stenberg Real Estate Group, your professional San Diego Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: John Stenberg
  title:
  license_number: 'CAL BRE#: 00980545'
  about_markdown: |
    With over 30 years of experience, John Stenberg has become San Diego's "Go to" agent and an active leader of his community. With a solid reputation for delivering his clients exceptional customer service from start to finish.  His local residential sales, marketing and negotiation experience join uncompromising integrity as the hallmarks of John's service.

    John is well respected in the Real Estate community not only for his unparalleled professional track record and high ethical standards but for being an honest, hard-working family man who does everything in his power to ensure his clients' success.  He understands the significance that any real estate venture can hold for your life. Thus he strives to provide both buyers and sellers with the level of professional services and personal attention that enhances every step of the experience. Expect a partner that not only has the knowledge and experience you need, but also makes himself available to answer all of your questions, address your concerns, manage solutions to all challenges and provide advice that is always in your best interests. You can continue to depend on John as a local resource and friend long after your real estate transaction is complete.

  market: San Diego
  brand: The Stenberg Real Estate Group
  brokerage:
#   address: 2300 Boswell Road. Suite 100 Chula Vista, CA 91914
  phone: 619-869-3838
  phone_type:
  phone2:
  phone2_type:
  email: john.stenberg@compass.com
  url:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://stenbergrealestate.com/home-valuation
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your San Diego Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://stenbergrealestate.com/home-valuation

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a San Diego Home?"
    CTA_text2: "Search the entire MLS for your San Diego home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheStenbergGroup/
  linkedin_url: https://www.linkedin.com/in/john-stenberg-aa99512b/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCDbCsiDfpymbVJDB0gOicdw
  twitter_url:
  instagram_url: https://www.instagram.com/johnstenberg_/?hl=en
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/John-Stenberg/
  trulia_url:
  yelp_url:
  podcast_url:
  google_business_url: https://g.page/r/CVfXCwu1KTWHEAE

podcast:
  title: 'San Diego Real Estate Podcast with John Stenberg'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Diego Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Stenberg Real Estate Group - your professional San Diego Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Diego, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'John Stenberg'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_logo_path2: /img/logo2.png
  logo_width_number: 40
  hero_text: San Diego Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#004B87'
  theme_color: '#939598'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
