audit_header: false
title: Chula Vista Real Estate Video Blog with John Stenberg
description: Our mission at The Stenberg Real Estate Group is to be your best resource for Chula Vista real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Stenberg Real Estate Group, your professional Chula Vista Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: John Stenberg
  title:
  license_number: 'CAL BRE#: 00980545'
  about_markdown: |
    With over 30 years of experience, John Stenberg has become San Diego's "Go to" agent and an active leader of his community. With a solid reputation for delivering his clients exceptional customer service from start to finish.  His local residential sales, marketing and negotiation experience join uncompromising integrity as the hallmarks of John's service.
  market: Chula Vista
  brand: The Stenberg Real Estate Group
  brokerage:
  address: 1073 Morgan Hill Drive
  phone: 619-869-3838
  phone_type:
  phone2:
  phone2_type:
  email: stenberg619@gmail.com
  url:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.newzestimate.com/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your Chula Vista Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.newzestimate.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a Chula Vista Home?"
    CTA_text2: "Search the entire MLS for your Chula Vista home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheStenbergGroup/
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Chula Vista Real Estate Podcast with John Stenberg'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Chula Vista Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Stenberg Real Estate Group - your professional Chula Vista Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Chula Vista, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'John Stenberg'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Chula Vista Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#004B87'
  theme_color: '#939598'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
